# SAMPLE
apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: chatbot
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: chatbotdb
      ports:
        - containerPort: 5432
