# SAMPLE
{
  "dashboard": {
    "id": null,
    "title": "Chatbot System Dashboard",
    "panels": [
      {
        "type": "graph",
        "title": "API Latency",
        "targets": [
          { "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))" }
        ]
      },
      {
        "type": "graph",
        "title": "Redis Cache Hit Ratio",
        "targets": [
          { "expr": "redis_keyspace_hits / (redis_keyspace_hits + redis_keyspace_misses)" }
        ]
      }
    ]
  }
}
